version: "3.9"
services:
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - my-network

  auth-layer:
    build:
      context: ./ 
      dockerfile: AuthLayer/Dockerfile
    ports:
      - "5151:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=postgres-db;Port=5432;Database=auth_layer;User Id=postgres;Password=password
    depends_on:
      - postgres-db
    networks:
      - my-network

  song-layer:
    build:
      context: ./
      dockerfile: SongLayer/Dockerfile
    ports:
      - "5555:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=postgres-db;Port=5432;Database=music_db;User Id=postgres;Password=password
    depends_on:
      - postgres-db
    networks:
      - my-network

  postgres-db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - my-network

volumes:
  postgres-data:

networks:
  my-network:
    driver: bridge
