name: Docker Compose CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Run Docker Compose
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Run Docker Compose
        run: |
          docker-compose up -d --build
          
      - name: Check running containers
        run: docker ps

      - name: Application Logs
        run: docker-compose logs

      - name: Stop Docker Compose
        if: always()
        run: docker-compose down
